### ISSUE TITLE
如何将下拉加载放在中间呢，不放在最上面

### ISSUE THREAD

**Issue by ThymeBoy** [Coder-ZJQ/WMPageController-JQHover#1]

**Comment by Coder-ZJQ** [comment]
可以将 [topBounceType](https://github.com/Coder-ZJQ/WMPageController-JQHover/blob/e6dd5bec3c564f9a10959cbdc83e56b9ac7c5599/WMPageController-JQHover/Classes/JQHoverFooterView.h#L25) 设置为 [JQHoverTopBounceTypeSub](https://github.com/Coder-ZJQ/WMPageController-JQHover/blob/e6dd5bec3c564f9a10959cbdc83e56b9ac7c5599/WMPageController-JQHover/Classes/JQHoverFooterView.h#L15)，然后在子页面添加刷新。
